In [1]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

In [2]:
import torch
print(torch.__version__)


2.8.0+cu126


In [3]:
if torch.cuda.is_available():
    print('Available')
    print(torch.cuda.get_device_name(0))
else:
    print("Not Available")

Not Available


In [4]:
torch.empty(2,3)

tensor([[6.1343e+07, 2.3822e-44, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 1.7957e-19]])

In [5]:
torch.arange(0,10,2)

tensor([0, 2, 4, 6, 8])

In [6]:
torch.zeros(2,3)

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [7]:
torch.ones(2,3)

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [8]:
torch.eye(5)

tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])

In [9]:
torch.rand(5,5)

tensor([[0.5671, 0.6857, 0.0094, 0.6506, 0.9613],
        [0.1034, 0.4754, 0.2088, 0.3425, 0.0178],
        [0.7618, 0.9896, 0.0089, 0.9760, 0.3703],
        [0.9733, 0.7370, 0.4587, 0.5500, 0.5607],
        [0.3844, 0.1765, 0.4673, 0.3498, 0.0567]])

In [10]:
torch.manual_seed(1000)

In [11]:
torch.rand(5,5)

tensor([[0.3189, 0.6136, 0.4418, 0.2580, 0.2724],
        [0.6261, 0.4410, 0.3653, 0.3535, 0.5971],
        [0.3572, 0.4807, 0.4217, 0.1254, 0.6818],
        [0.0571, 0.6818, 0.0473, 0.4856, 0.0260],
        [0.0131, 0.7607, 0.0722, 0.1026, 0.3915]])

In [12]:
torch.tensor([[1,2,3],[4,5,6]])

tensor([[1, 2, 3],
        [4, 5, 6]])

In [13]:
x = torch.tensor([[1,2,3],[4,5,6]])

In [14]:
x.shape

torch.Size([2, 3])

In [15]:
type(x)

torch.Tensor

In [16]:
torch.empty_like(x)

tensor([[3616445622929465956, 6068936043043761462, 3616454483765769776],
        [6500726392571376686, 7309453675965983778, 8315168162784306286]])

In [17]:
torch.ones_like(x)

tensor([[1, 1, 1],
        [1, 1, 1]])

In [18]:
torch.zeros_like(x)

tensor([[0, 0, 0],
        [0, 0, 0]])

In [19]:
x.dtype

torch.int64

In [20]:
torch.rand_like(x)

NotImplementedError: "check_uniform_bounds" not implemented for 'Long'

In [ ]:
torch.rand_like(x, dtype=torch.float64)

In [ ]:
y = torch.rand(5,5)

In [ ]:
y

In [ ]:
y + 2

In [ ]:
y - 1

In [ ]:
y * 100

In [ ]:
torch.abs(y)

In [ ]:
torch.negative(y)

In [ ]:
torch.sqrt(y)

In [ ]:
torch.round(y)

In [ ]:
torch.ceil(y)

In [ ]:
torch.floor(y)

In [ ]:
torch.clamp(y, min = 0, max = 1)

In [ ]:
torch.sum(y)

In [ ]:
torch.mean(y)

In [ ]:
torch.median(y)

In [ ]:
torch.argmax(y)

In [ ]:
torch.argmin(y)

In [ ]:
torch.std(y)

In [ ]:
torch.var(y)

In [ ]:
torch.log(y)

In [ ]:
torch.sigmoid(y)

In [ ]:
torch.det(y)

In [ ]:
torch.exp(y)

In [ ]:
torch.relu(y)

In [ ]:
torch.min(y)

In [ ]:
torch.max(y)